site_name: OSG Site Documentation
site_url: https://opensciencegrid.org/docs/
repo_url: https://github.com/opensciencegrid/docs/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'
  features:
    - navigation.tabs

extra_css:
  - css/extra.css

nav:
- Home: 'index.md'
- Detailed Overview: 'detailed-overview.md'
- Site Planning: 'site-planning.md'
- Site Verification: 'site-verification.md'
- Site Responsibilities: 'site-responsibilities.md'
- Resource Sharing:
  - Compute:
    - 'Overview': 'resource-sharing/overview.md'
    - 'Site Backfill': 'resource-sharing/os-backfill-containers.md'
    - 'User Allocations': 'resource-sharing/user-containers.md'
    - Compute Entrypoint:
      - 'HTCondor-CE Overview': 'compute-element/htcondor-ce-overview.md'
      - 'Request a Hosted CE': 'compute-element/hosted-ce.md'
      - 'Install HTCondor-CE': 'compute-element/install-htcondor-ce.md'
      - 'Job Router Recipes': 'compute-element/job-router-recipes.md'
      - 'Troubleshooting HTCondor-CE': 'compute-element/troubleshoot-htcondor-ce.md'
      - 'Submitting to HTCondor-CE': 'compute-element/submit-htcondor-ce.md'
      - 'Supporting COVID-19 Research': 'compute-element/covid-19.md'
    - Worker Node:
        - 'Overview': 'worker-node/using-wn.md'
        - 'Install from RPM': 'worker-node/install-wn.md'
        - 'Install from Tarball': 'worker-node/install-wn-tarball.md'
        - 'Install from OASIS': 'worker-node/install-wn-oasis.md'
        - 'Install CVMFS': 'worker-node/install-cvmfs.md'
        - 'Install Singularity': 'worker-node/install-singularity.md'
        - 'Using WN Containers': 'worker-node/using-wn-containers.md'
  - Data:
    - HTTP & OASIS:
      - 'Running Frontier Squid in a Container': 'data/run-frontier-squid-container.md'
      - 'Install Frontier Squid RPM': 'data/frontier-squid.md'
      - 'Update OASIS Shared Repo': 'data/update-oasis.md'
      - 'Install an OASIS Repo': 'data/external-oasis-repos.md'
    - XRootD:
      - 'XRootD Overview': 'data/xrootd/overview.md'
      - 'Install XRootD Standalone': 'data/xrootd/install-standalone.md'
      - 'Install XRootD SE': 'data/xrootd/install-storage-element.md'
      - 'Configure Authorization': 'data/xrootd/xrootd-authorization.md'
      - 'Using XRootD': 'data/xrootd/install-client.md'
      - 'Install CMS XCache': 'data/xrootd/install-cms-xcache.md'
    - StashCache:
      - 'StashCache Overview': 'data/stashcache/overview.md'
      - 'Running a Cache in a container': 'data/stashcache/run-stashcache-container.md'
      - 'Running an Origin in a container': 'data/stashcache/run-stash-origin-container.md'
      - 'Install a Cache': 'data/stashcache/install-cache.md'
      - 'Install an Origin': 'data/stashcache/install-origin.md'
      - 'Getting VO data into StashCache': 'data/stashcache/vo-data.md'
  - Other:
    - 'Configuration with OSG-Configure': 'other/configuration-with-osg-configure.md'
    - 'Install GlideinWMS Frontend': 'other/install-gwms-frontend.md'
    - 'Install a CVMFS Stratum 1': 'other/install-cvmfs-stratum1.md'
    - 'Troubleshooting Gratia': 'other/troubleshooting-gratia.md'
    - 'Install Transfer Log Filebeats': 'other/schedd-filebeats.md'
  - Deprecated:
    - POSIX Storage:
      - 'Install GridFTP Server': 'data/gridftp.md'
      - 'Install Load Balanced GridFTP': 'data/load-balanced-gridftp.md'
    - HDFS:
      - 'HDFS Overview': 'data/hadoop-overview.md'
      - 'Install HDFS': 'data/install-hadoop.md'
    - Security:
      - 'LCMAPS VOMS authentication': 'security/lcmaps-voms-authentication.md'
      - 'User Certificates': 'security/user-certs.md'
    - 'Install GSI-enabled SSH': 'other/gsissh.md'
    - 'Install RSV': 'monitoring/install-rsv.md'
    - 'Advanced RSV Configuration': 'monitoring/advanced-rsv-configuration.md'
    - 'Manage RSV via rsv-control': 'monitoring/rsv-control.md'
    - 'RSV GlideinWMS Tester': 'monitoring/install-rsv-gwms-tester.md'
- Submit:
  - 'Flocking to OSG': 'submit/osg-flock.md'
- Common:
  - Security:
    - 'CA Certificates': 'common/ca.md'
    - 'Certificate Management Reference': 'security/certificate-management.md'
    - 'Host Certificates':
      - 'Overview': 'security/host-certs/overview.md'
      - 'Using InCommon': 'security/host-certs/incommon.md'
      - "Using Let's Encrypt": 'security/host-certs/lets-encrypt.md'
      - 'Using DigiCert': 'security/host-certs/digicert.md'
  - 'OSG Yum Repos': 'common/yum.md'
  - 'Registration': 'common/registration.md'
- Releases:
  - 'Release Note Overview': 'release/notes.md'
  - 3.5 Release Notes:
    - 'OSG Release 3.5.30': 'release/3.5/release-3-5-30.md'
    - 'OSG Release 3.5.29': 'release/3.5/release-3-5-29.md'
    - 'OSG Release 3.5.28-2': 'release/3.5/release-3-5-28-2.md'
    - 'OSG Release 3.5.28': 'release/3.5/release-3-5-28.md'
    - 'OSG Release 3.5.27': 'release/3.5/release-3-5-27.md'
    - 'OSG Release 3.5.26': 'release/3.5/release-3-5-26.md'
    - 'OSG Release 3.5.25-2': 'release/3.5/release-3-5-25-2.md'
    - 'OSG Release 3.5.25': 'release/3.5/release-3-5-25.md'
    - 'OSG Release 3.5.24': 'release/3.5/release-3-5-24.md'
    - 'OSG Release 3.5.23': 'release/3.5/release-3-5-23.md'
    - 'OSG Release 3.5.22': 'release/3.5/release-3-5-22.md'
    - 'OSG Release 3.5.21-2': 'release/3.5/release-3-5-21-2.md'
    - 'OSG Release 3.5.21': 'release/3.5/release-3-5-21.md'
    - 'OSG Release 3.5.20': 'release/3.5/release-3-5-20.md'
    - 'OSG Release 3.5.19': 'release/3.5/release-3-5-19.md'
    - 'OSG Release 3.5.18': 'release/3.5/release-3-5-18.md'
    - 'OSG Release 3.5.17': 'release/3.5/release-3-5-17.md'
    - 'OSG Release 3.5.16': 'release/3.5/release-3-5-16.md'
    - 'OSG Release 3.5.15-3': 'release/3.5/release-3-5-15-3.md'
    - 'OSG Release 3.5.15-2': 'release/3.5/release-3-5-15-2.md'
    - 'OSG Release 3.5.15': 'release/3.5/release-3-5-15.md'
    - 'OSG Release 3.5.14': 'release/3.5/release-3-5-14.md'
    - 'OSG Release 3.5.13': 'release/3.5/release-3-5-13.md'
    - 'OSG Release 3.5.12': 'release/3.5/release-3-5-12.md'
    - 'OSG Release 3.5.11': 'release/3.5/release-3-5-11.md'
    - 'OSG Release 3.5.10-2': 'release/3.5/release-3-5-10-2.md'
    - 'OSG Release 3.5.10': 'release/3.5/release-3-5-10.md'
    - 'OSG Release 3.5.9': 'release/3.5/release-3-5-9.md'
    - 'OSG Release 3.5.8-4': 'release/3.5/release-3-5-8-4.md'
    - 'OSG Release 3.5.8-3': 'release/3.5/release-3-5-8-3.md'
    - 'OSG Release 3.5.8-2': 'release/3.5/release-3-5-8-2.md'
    - 'OSG Release 3.5.8': 'release/3.5/release-3-5-8.md'
    - 'OSG Release 3.5.7': 'release/3.5/release-3-5-7.md'
    - 'OSG Release 3.5.6': 'release/3.5/release-3-5-6.md'
    - 'OSG Release 3.5.5': 'release/3.5/release-3-5-5.md'
    - 'OSG Release 3.5.4': 'release/3.5/release-3-5-4.md'
    - 'OSG Release 3.5.3': 'release/3.5/release-3-5-3.md'
    - 'OSG Release 3.5.2': 'release/3.5/release-3-5-2.md'
    - 'OSG Release 3.5.1': 'release/3.5/release-3-5-1.md'
    - 'OSG Release 3.5.0': 'release/3.5/release-3-5-0.md'
  - 'OSG Release Series': 'release/release_series.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
  - 'Yum Basics': 'release/yum-basics.md'
  - 'RPM Signing': 'release/signing.md'
- Help:
  - 'Getting Help': 'common/help.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - toc:
      permalink: True
