site_name: OSG Documentation
site_url: https://djw8605.github.io/osg-docs/
repo_url: https://github.com/djw8605/osg-docs/
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Install Guides:
  - 'Yum Repos': 'Common/yum.md'
  - 'HTCondor-CE': 'Computing_Element/HTCondor_CE.md'
  - 'HTTP Cache': 'Frontier_Squid/squid.md'
  - 'GSI-enabled SSH': 'Other/gsissh.md'
  - 'Worker Node': 'Other/wn.md'
  - 'Worker node glexec': 'Other/glexec.md'

markdown_extensions:
  - admonition

