site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/docs
repo_url: https://github.com/opensciencegrid/docs
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Installation Overview: 'install-overview.md'
- Install Guides - Common:
  - 'CA Certificates': 'common/ca.md'
  - 'Yum Repos': 'common/yum.md'
- Install Guides - Worker Node:
  - 'Worker Node (RPM install)': 'worker-node/install-wn.md'
  - 'Worker Node (tarball install)': 'worker-node/install-wn-tarball.md'
  - 'Worker Node (OASIS install)': 'worker-node/install-wn-oasis.md'
  - 'CVMFS': 'worker-node/install-cvmfs.md'
  - 'Singularity': 'worker-node/install-singularity.md'
- Compute Element:
  - 'HTCondor-CE Overview': 'compute-element/htcondor-ce-overview.md'
  - 'Install HTCondor-CE': 'compute-element/install-htcondor-ce.md'
  - 'Job Router Recipes': 'compute-element/job-router-recipes.md'
  - 'Troubleshooting HTCondor-CE': 'compute-element/troubleshoot-htcondor-ce.md'
  - 'Submitting to HTCondor-CE': 'compute-element/submit-htcondor-ce.md'
- Install Guides - Data:
  - 'GridFTP Server': 'data/gridftp.md'
  - 'HTTP Cache': 'data/frontier-squid.md'
- Install Guides - Other:
  - 'GSI-enabled SSH': 'other/gsissh.md'
  - 'LCMAPS-VOMS authentication': 'security/lcmaps-voms-authentication.md'
  - 'OSG upcoming software': 'other/install-osg-upcoming-software.md'
- Monitoring:
  - 'RSV Overview': 'monitoring/rsv-overview.md'
  - 'Install RSV': 'monitoring/install-rsv.md'
  - 'Configure RSV': 'monitoring/configure-rsv.md'
  - 'Manage RSV via rsv-control': 'monitoring/rsv-control.md'
  - 'RSV GlideinWMS Tester': 'monitoring/install-rsv-gwms-tester.md'
- Install Guides - Other:
  - 'Install Best Practices': 'common/install-best-practices.md'
  - 'GSI-enabled SSH': 'other/gsissh.md'
  - 'LCMAPS-VOMS authentication': 'security/lcmaps-voms-authentication.md'
  - 'GlideinWMS Frontend': 'other/install-gwms-frontend.md'
- Release Information:
  - 'OSG Release Series': 'release/release_series.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
  - 'Yum Basics': 'release/yum-basics.md'
  - 'RPM Signing': 'release/signing.md'
  - 'Contrib Software': 'release/contrib.md'
- Usage Guides:
  - 'Certificate Tools': 'common/pki-cli.md'
  - 'Configuration with OSG-Configure': 'other/configuration-with-osg-configure.md'
  - 'Worker Node Environment': 'worker-node/using-wn.md'
- Deprecated Software:
  - 'BeStMan Overview': 'data/bestman-overview.md'
  - 'BeStMan Install': 'data/bestman-install.md'
  - 'EDG-Mkgridmap Install': 'security/edg-mkgridmap.md'
  - 'GUMS': 'security/install-gums.md'
  - 'Worker node glexec Install': 'worker-node/install-glexec.md'
- 'Get Help': 'common/help.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors
