site_name: OSG Documentation
site_url: https://djw8605.github.io/osg-docs/
repo_url: https://github.com/djw8605/osg-docs/
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Admin Guide:
  - 'HTCondor-CE Install': 'Computing_Element/HTCondor_CE.md'
  - 'Squid Install': 'Frontier_Squid/squid.md'
  - 'Yum Repos': 'Common/yum.md'

