site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/docs
repo_url: https://github.com/opensciencegrid/docs
theme: readthedocs
theme_dir: osgthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Installation Overview: 'install-overview.md'
- Install Guides - Common:
  - 'CA Certificates': 'common/ca.md'
  - 'Yum Repos': 'common/yum.md'
- Install Guides - Client:
  - 'Worker Node (RPM install)': 'client/wn.md'
  - 'Worker Node (tarball install)': 'client/wn-tarball.md'
  - 'Worker Node (OASIS install)': 'client/wn-oasis.md'
  - 'CVMFS': 'client/cvmfs.md'
  - 'Singularity': 'client/singularity.md'
- Install Guides - Compute:
  - 'HTCondor-CE': 'compute-element/install-htcondor-ce.md'
- Install Guides - Data:
  - 'GridFTP Server': 'data/gridftp.md'
  - 'HTTP Cache': 'data/frontier-squid.md'
- Install Guides - Other:
  - 'GSI-enabled SSH': 'other/gsissh.md'
  - 'LCMAPS-VOMS authentication': 'security/lcmaps-voms-authentication.md'
  - 'OSG upcoming software': 'other/install-osg-upcoming-software.md'
- Install Guides - Monitoring:
  - 'RSV': 'monitoring/rsv.md'
  - 'RSV GlideinWMS Tester': 'monitoring/rsv-gwms-tester.md'
- Install Guides - Other:
  - 'GSI-enabled SSH': 'other/gsissh.md'
  - 'LCMAPS-VOMS authentication': 'security/lcmaps-voms-authentication.md'
- Overviews:
  - 'HTCondor-CE': 'compute-element/htcondor-ce-overview.md'
- Release Information:
  - 'Release Notes': 'release/notes.md'
  - 'OSG Release Series': 'release/release_series.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
  - 'Yum Basics': 'release/yum-basics.md'
  - 'RPM Signing': 'release/signing.md'
- Usage Guides:
  - 'Certificate Tools': 'common/pki-cli.md'
  - 'Configuration with OSG-Configure': 'other/configuration-with-osg-configure.md'
  - 'Worker Node Environment': 'client/using-wn.md'
- In-Progress Docs:
  - 'CA Updater': 'common/ca_updater.md'
  - 'Certificate Request Scripts': 'common/cert_scripts.md'
  - 'Job Router Recipe': 'compute-element/job_router.md'
- Deprecated Software:
  - 'BeStMan Overview': 'data/bestman-overview.md'
  - 'BeStMan Install': 'data/bestman-install.md'
  - 'EDG-Mkgridmap Install': 'security/edg-mkgridmap.md'
  - 'GUMS': 'security/install-gums.md'
  - 'Worker node glexec Install': 'client/glexec.md'
- 'Get Help': 'common/help.md'
- 'OSG Release 3.4.3': 'release/3.4/release-3-4-3.md'
- 'OSG Release 3.3.28': 'release/3.3/release-3-3-28.md'
- 'OSG Release 3.4.2-2': 'release/3.4/release-3-4-2-2.md'
- 'OSG Release 3.4.2': 'release/3.4/release-3-4-2.md'
- 'OSG Release 3.4.1-2': 'release/3.4/release-3-4-1-2.md'
- 'OSG Release 3.4.1': 'release/3.4/release-3-4-1.md'
- 'OSG Release 3.4.0-2': 'release/3.4/release-3-4-0-2.md'
- 'OSG Release 3.4.0': 'release/3.4/release-3-4-0.md'
- 'OSG Release 3.3.27': 'release/3.3/release-3-3-27.md'
- 'OSG Release 3.3.26': 'release/3.3/release-3-3-26.md'
- 'OSG Release 3.3.25': 'release/3.3/release-3-3-25.md'
- 'OSG Release 3.3.24-2': 'release/3.3/release-3-3-24-2.md'
- 'OSG Release 3.3.24': 'release/3.3/release-3-3-24.md'
- 'OSG Release 3.3.23': 'release/3.3/release-3-3-23.md'
- 'OSG Release 3.3.22-3': 'release/3.3/release-3-3-22-3.md'
- 'OSG Release 3.3.22-2': 'release/3.3/release-3-3-22-2.md'
- 'OSG Release 3.3.22': 'release/3.3/release-3-3-22.md'
- 'OSG Release 3.3.21-3': 'release/3.3/release-3-3-21-3.md'
- 'OSG Release 3.3.21-2': 'release/3.3/release-3-3-21-2.md'
- 'OSG Release 3.3.21': 'release/3.3/release-3-3-21.md'
- 'OSG Release 3.3.20-2': 'release/3.3/release-3-3-20-2.md'
- 'OSG Release 3.3.20': 'release/3.3/release-3-3-20.md'
- 'OSG Release 3.3.19': 'release/3.3/release-3-3-19.md'
- 'OSG Release 3.3.18': 'release/3.3/release-3-3-18.md'
- 'OSG Release 3.3.17-2': 'release/3.3/release-3-3-17-2.md'
- 'OSG Release 3.3.17': 'release/3.3/release-3-3-17.md'
- 'OSG Release 3.3.16': 'release/3.3/release-3-3-16.md'
- 'OSG Release 3.3.15': 'release/3.3/release-3-3-15.md'
- 'OSG Release 3.3.14': 'release/3.3/release-3-3-14.md'
- 'OSG Release 3.3.13': 'release/3.3/release-3-3-13.md'
- 'OSG Release 3.3.12': 'release/3.3/release-3-3-12.md'
- 'OSG Release 3.3.11': 'release/3.3/release-3-3-11.md'
- 'OSG Release 3.3.10': 'release/3.3/release-3-3-10.md'
- 'OSG Release 3.3.9': 'release/3.3/release-3-3-9.md'
- 'OSG Release 3.3.8': 'release/3.3/release-3-3-8.md'
- 'OSG Release 3.3.7': 'release/3.3/release-3-3-7.md'
- 'OSG Release 3.3.6': 'release/3.3/release-3-3-6.md'
- 'OSG Release 3.3.5': 'release/3.3/release-3-3-5.md'
- 'OSG Release 3.3.4': 'release/3.3/release-3-3-4.md'
- 'OSG Release 3.3.3': 'release/3.3/release-3-3-3.md'
- 'OSG Release 3.3.2': 'release/3.3/release-3-3-2.md'
- 'OSG Release 3.3.1': 'release/3.3/release-3-3-1.md'
- 'OSG Release 3.3.0': 'release/3.3/release-3-3-0.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors

