site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/docs
repo_url: https://github.com/opensciencegrid/docs
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Installation Overview: 'install-overview.md'
- Install Guides:
  - 'Yum Repos': 'common/yum.md'
  - 'CA Certificates': 'common/ca.md'
  - 'HTCondor-CE': 'compute-element/HTCondor_CE.md'
  - 'HTTP Cache': 'frontier-squid/squid.md'
  - 'CVMFS': 'client/cvmfs.md'
  - 'GSI-enabled SSH': 'other/gsissh.md'
  - 'RPM-based Worker Node': 'client/wn.md'
  - 'Worker node glexec': 'client/glexec.md'
- Release Information:
  - 'OSG Release Series': 'release/release_series.md'
  - 'RPM Signing': 'release/signing.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
- In-Progress Docs:
  - 'CA Updater': 'common/ca_updater.md'
  - 'Certificate Request Scripts': 'common/cert_scripts.md'
  - 'Job Router Recipe': 'compute-element/job_router.md'
  - 'OASIS-based Worker Node': 'client/wn_oasis.md'
  - 'GridFTP Server': 'storage/gridftp.md'
- Deprecated Software:
  - 'BeStMan Overview': 'storage/bestman-overview.md'

markdown_extensions:
  - admonition
  - codehilite
  - osg_markdown.colors

